FROM node:20-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY ./package.json .
COPY ./package-lock.json .

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

RUN npm i

# Copy in the source
COPY . .

# Run the app
# TODO: need to figure out the necessary of all parameters
CMD npm start --host 0.0.0.0 --port 3000 --disableHostCheck true