FROM node:20-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY ./package.json .
COPY ./package-lock.json .
RUN npm install

# Copy in the source
COPY . .

# Run the app
CMD ["npm", "start"]