FROM node:20-alpine

ARG FRONTEND_PORT

# Create app directory
WORKDIR /app

# Install app dependencies
COPY ./package.json .
COPY ./package-lock.json .

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

RUN npm i

# Copy in the source
COPY . .

# Run the app
CMD npm start --host 0.0.0.0 --port ${FRONTEND_PORT} --disableHostCheck true