#!/bin/sh

BACKUP_FOLDER_PATH=$BACKUP_FOLDER_PATH
NOW=$(date +%F_%H-%M-%S)

GZIP=$(which gzip)
MYSQLDUMP=$(which mysqldump)

### MySQL Server Login info ###
MDB=$MYSQL_DATABASE
MHOST=$MYSQL_CONTAINER_NAME
MPASS=$MYSQL_ROOT_PASSWORD
MUSER=root

[ ! -d "$BACKUP_FOLDER_PATH" ] && mkdir --parents $BACKUP_FOLDER_PATH

FILE=${BACKUP_FOLDER_PATH}/backup-${NOW}.sql.gz
$MYSQLDUMP -h $MHOST -u $MUSER -p${MPASS} --databases $MDB | $GZIP -9 > $FILE
