import { Field, Int, ObjectType } from '@nestjs/graphql';
import { Invoice } from 'src/invoice/entities/invoice.entity';
import {
  Column,
  Entity,
  OneToMany,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

@Entity()
@ObjectType()
export class User {
  @PrimaryGeneratedColumn()
  @Field(() => Int, { nullable: false })
  id: number;

  @Column({ type: 'varchar', nullable: false })
  @Field(() => String, { nullable: false })
  username: string;

  @Column({ type: 'varchar', nullable: false })
  @Field(() => String, { nullable: false })
  password: string;

  @Column({ type: 'int', nullable: false })
  @Field(() => Int, { nullable: false }) // TODO: use default and create enum also generated by graphql
  role: number;

  @UpdateDateColumn({ type: 'timestamp', nullable: false })
  @Field(() => Date, { nullable: false })
  modified: Date;

  @Column({
    type: 'timestamp',
    default: () => 'CURRENT_TIMESTAMP',
    nullable: false,
  })
  @Field(() => Date, { nullable: false })
  created: Date;

  @OneToMany(() => Invoice, (invoice) => invoice.customer, {
    nullable: true,
  })
  @Field(() => [Invoice], { nullable: true })
  invoices?: Invoice[];
}
