import { Field, InputType, Int } from '@nestjs/graphql';

@InputType()
export class CreateInvoiceInput {
  @Field(() => String, { nullable: false })
  title: string;

  @Field(() => Int, { nullable: true })
  discount?: string; // TODO: figure out how to use this?

  @Field(() => Int, { nullable: false }) // TODO: use default and create enum also generated by graphql
  payedBy: number;

  @Field(() => String, { nullable: true })
  additionalInfo: string;

  @Field(() => Int, { nullable: true })
  clientId?: number;

  @Field(() => Int, { nullable: true })
  userId?: number;

  @Field(() => Int, { nullable: true })
  customerId?: number;
}
